# Generated by Django 5.2.1 on 2026-07-07 00:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.RemoveConstraint(
            model_name="customuser",
            name="unique_email_username",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(error_messages={"unique": "User with this email already exists."}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                error_messages={"unique": "User with this username already exists."},
                max_length=8,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Only letters, numbers, underscores and dots are allowed.", regex="^[a-zA-Z0-9_.]+$"
                    )
                ],
            ),
        ),
    ]
