# Generated by Django 5.2.1 on 2025-10-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="verification_code",
            field=models.IntegerField(null=True),
        ),
    ]
