# Generated by Django 5.2.1 on 2025-10-15 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_customuser_verification_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailverification",
            name="expires_at",
        ),
        migrations.RemoveField(
            model_name="passwordresetcode",
            name="expires_at",
        ),
    ]
