# Generated by Django 5.2.1 on 2025-10-15 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_emailverification_expires_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverification",
            name="code",
            field=models.IntegerField(max_length=6),
        ),
        migrations.AlterField(
            model_name="passwordresetcode",
            name="code",
            field=models.IntegerField(max_length=6),
        ),
    ]
