# Generated by Django 5.2.1 on 2025-10-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_emailverification_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverification",
            name="code",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="passwordresetcode",
            name="code",
            field=models.IntegerField(null=True),
        ),
    ]
