# Generated by Django 5.2.1 on 2025-09-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("artist_name", models.CharField(max_length=255)),
                ("duration", models.FloatField()),
                ("audio_file", models.URLField()),
                ("cover_image", models.URLField()),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("uploaded_by", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["-upload_date"],
            },
        ),
    ]
