# Generated by Django 5.2.1 on 2025-09-30 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="upload_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
