# Generated by Django 5.2.1 on 2025-09-30 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0002_alter_song_upload_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="audio_file",
            field=models.FileField(upload_to="Songs/"),
        ),
        migrations.AlterField(
            model_name="song",
            name="cover_image",
            field=models.FileField(upload_to="SongsCovers/"),
        ),
    ]
