# Generated by Django 5.2.1 on 2026-07-03 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0002_playlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="cover_image",
        ),
    ]
