# Generated by Django 5.2.1 on 2026-07-03 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0003_remove_song_cover_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Playlist",
        ),
    ]
