# Generated by Django 5.2.1 on 2025-10-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0003_alter_song_audio_file_alter_song_cover_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="audio_file",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="song",
            name="cover_image",
            field=models.URLField(),
        ),
    ]
