# Generated by Django 5.2.1 on 2025-10-04 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0004_alter_song_audio_file_alter_song_cover_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
