# Generated by Django 5.2.1 on 2026-07-04 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0004_delete_playlist"),
    ]

    operations = [
        migrations.RenameField(
            model_name="song",
            old_name="audio_file",
            new_name="audio_url",
        ),
    ]
