# Generated by Django 5.2.1 on 2026-07-07 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0005_rename_audio_file_song_audio_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Playlist",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("playlist_name", models.CharField(max_length=255)),
                ("created_date", models.DateField(auto_now_add=True)),
                (
                    "playlist_owner",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="playlists", to=settings.AUTH_USER_MODEL),
                ),
                ("songs", models.ManyToManyField(blank=True, related_name="playlists", to="songs.song")),
            ],
        ),
    ]
